networks:
  backend:
    driver: bridge
  api:
    driver: bridge

services:

  #Proxied And Gateway
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/ssl
    ports:
      - "443:443"
    networks:
      - backend
    restart: unless-stopped
  
  krakend:
    image: krakend:2.11
    container_name: krakend-gateway
    volumes:
      - ./krakend/krakend.json:/etc/krakend/krakend.json
    expose:
      - "8080"
    networks:
      - backend
      - api
    restart: unless-stopped


  #Services
  worker:
    build: 
      context: ./worker
      dockerfile: dockerfile
    container_name: worker-service
    networks:
      - api
    restart: unless-stopped
    expose:
      - "8080"

